package org.austindroids.knoppen.sqlgen

import org.austindroids.knoppen.ResourceConstants
import org.austindroids.knoppen.datafile.DataFileLoader
import org.austindroids.knoppen.datafile.DataFileLoaderFactory
import org.austindroids.knoppen.datafile.DataFileValidator
import org.austindroids.knoppen.datafile.DataValidationError
import org.austindroids.knoppen.datafile.ForeignKeyValidator
import org.austindroids.knoppen.schema.DatabaseSchema
import org.austindroids.knoppen.schema.DefaultType
import org.austindroids.knoppen.schema.TableSchema
import tools.jackson.databind.JsonNode
import java.nio.file.Path
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import kotlin.io.path.extension
import kotlin.io.path.readText

/**
 * A [ColumnGenerator] produces one value per call to [next].
 * Generators are stateful and tied to one column in one generation run.
 */
interface ColumnGenerator {
    fun next(rowIndex: Int): Any?
    fun reset()
}

/**
 * Orchestrates the full schema-driven pipeline:
 *
 *   Topological sort → Load data files → Validate → Generate SQL
 *
 * Entry point: [generateAll] reads each table's declared data files from the
 * filesystem, merges multi-file tables, runs structural and FK validation, then
 * produces SQL statements in dependency order.
 *
 * Returns a [GenerationResult] containing any errors and, when there are no
 * hard errors, the generated SQL statements.
 */
class UpsertGenerator(
    private val dbSchema: DatabaseSchema,
    private val dialect: SqlDialect
) {
    // ─────────────────────────────────────────────────────────────────────────
    // Result types
    // ─────────────────────────────────────────────────────────────────────────

    data class FileStats(
        val filePath: String,
        val tableName: String,
        val rowCount: Int
    )

    data class GenerationResult(
        val errors: List<DataValidationError>,
        val sql: List<NamedStatement>,
        val fileStats: List<FileStats> = emptyList()
    ) {
        data class NamedStatement(
            val table: String,
            val rowIndex: Int,
            val sql: String
        )

        val hasErrors: Boolean get() = errors.any {
            it.severity == DataValidationError.Severity.ERROR
        }

        fun prettyPrint(): String = buildString {
            if (errors.isNotEmpty()) {
                val (errs, warns) = errors.partition {
                    it.severity == DataValidationError.Severity.ERROR
                }
                if (errs.isNotEmpty()) {
                    appendLine("❌ ${errs.size} validation error(s):")
                    errs.forEach { appendLine("   $it") }
                }
                if (warns.isNotEmpty()) {
                    appendLine("⚠️  ${warns.size} warning(s):")
                    warns.forEach { appendLine("   $it") }
                }
            }
            if (sql.isNotEmpty()) {
                appendLine()
                appendLine(sqlHeader())
                sql.forEach { stmt ->
                    appendLine()
                    appendLine("-- Table: ${stmt.table}, row[${stmt.rowIndex}]")
                    appendLine(stmt.sql)
                }
            }
        }

        fun toSqlString(): String = buildString {
            appendLine(sqlHeader())
            sql.forEach { stmt ->
                appendLine()
                appendLine("-- Table: ${stmt.table}, row[${stmt.rowIndex}]")
                appendLine(stmt.sql)
            }
        }

        private fun sqlHeader(): String {
            val now       = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
            val user      = System.getProperty("user.name", "unknown")
            val appName   = ResourceConstants.APP_NAME
            val version   = ResourceConstants.APP_VERSION
            val byCounts  = sql.groupBy { it.table }
                .entries
                .joinToString("\n") { (table, stmts) ->
                    "--   %-20s %d statement(s)".format("$table:", stmts.size)
                }
            return """
                |-- ============================================================
                |-- Generated by $appName version $version
                |-- User:      $user
                |-- Generated: $now
                |-- ------------------------------------------------------------
                |-- Tables:
                |$byCounts
                |-- ============================================================
            """.trimMargin()
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Schema-driven pipeline
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Runs the full pipeline driven by the schema's `files:` declarations.
     *
     * @param schemaPath          Path to the schema file; its parent directory is the base for
     *                            resolving [DatabaseSchema.rootDataPath] and relative file entries.
     * @param rootDataPathOverride When non-null, replaces the schema's `rootDataPath` entirely.
     * @param generateSql         When false, skips SQL generation (validate-only mode).
     */
    fun generateAll(
        schemaPath: Path,
        rootDataPathOverride: Path? = null,
        generateSql: Boolean = true
    ): GenerationResult {
        val schemaDir   = schemaPath.parent
        val baseDataDir = when {
            rootDataPathOverride != null -> rootDataPathOverride
            dbSchema.rootDataPath != null -> schemaDir.resolve(dbSchema.rootDataPath).normalize()
            else -> schemaDir
        }

        // ── 1. Topological sort ────────────────────────────────────────────────
        val sortedTables: List<TableSchema> = try {
            TableDependencyResolver(dbSchema).sort()
        } catch (e: TableDependencyResolver.CyclicDependencyException) {
            return GenerationResult(
                errors = listOf(DataValidationError(
                    table    = "",
                    rowIndex = -1,
                    field    = null,
                    line     = null,
                    message  = e.message ?: "Cycle detected in table dependencies"
                )),
                sql = emptyList()
            )
        }

        val allErrors    = mutableListOf<DataValidationError>()
        val allRows      = mutableMapOf<String, List<JsonNode>>()
        val allFileStats = mutableListOf<FileStats>()

        // ── 2. Load, merge, and validate each table ────────────────────────────
        for (tableSchema in sortedTables) {
            val (tableRows, tableErrors, fileStats) = loadAndValidateTable(tableSchema, baseDataDir)
            allErrors.addAll(tableErrors)
            allRows[tableSchema.tableName] = tableRows
            allFileStats.addAll(fileStats)
        }

        // ── 3. Cross-table FK integrity ────────────────────────────────────────
        val fkErrors = ForeignKeyValidator(dbSchema, allRows).validate()
        allErrors.addAll(fkErrors)

        // ── 4. Generate SQL (only when no hard errors and generateSql=true) ────
        val statements = if (!generateSql || allErrors.any { it.severity == DataValidationError.Severity.ERROR }) {
            emptyList()
        } else {
            buildAllStatements(sortedTables, allRows)
        }

        return GenerationResult(allErrors, statements, allFileStats)
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Internal helpers
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Loads all declared files for [tableSchema], merges their rows, detects
     * duplicate primary keys across files, and runs structural validation.
     *
     * Returns a triple of (merged rows, validation errors, per-file stats).
     */
    private fun loadAndValidateTable(
        tableSchema: TableSchema,
        baseDataDir: Path
    ): Triple<List<JsonNode>, List<DataValidationError>, List<FileStats>> {

        val errors    = mutableListOf<DataValidationError>()
        val tableRows = mutableListOf<JsonNode>()
        val fileStats = mutableListOf<FileStats>()
        // Tracks PKs seen in previously-processed files — intra-file duplicates are
        // intentional (ON CONFLICT test rows) and must not trigger this check.
        val pkValuesFromPreviousFiles = mutableSetOf<String>()
        var mergedLineIndex = DataFileLoader.LineIndex.EMPTY

        for (filePath in tableSchema.files) {
            val fullPath = baseDataDir.resolve(filePath).normalize()
            val content  = fullPath.readText()
            val ext      = fullPath.extension

            val loader     = DataFileLoaderFactory.forExtension(ext)
            val loadResult = loader.load(content, tableSchema.tableName)
            val rowOffset  = tableRows.size

            // ── Structural validation per file ─────────────────────────────
            val fileErrors = DataFileValidator(
                dbSchema  = dbSchema,
                tableName = tableSchema.tableName,
                rows      = loadResult.rows,
                lineIndex = loadResult.lineIndex
            ).validate()

            // Re-offset row indices to merged position
            errors.addAll(fileErrors.map { err ->
                if (err.rowIndex >= 0) err.copy(rowIndex = err.rowIndex + rowOffset) else err
            })

            // ── Duplicate PK detection across files ────────────────────────
            val thisFilePkKeys = mutableSetOf<String>()
            for ((localIdx, row) in loadResult.rows.withIndex()) {
                val globalIdx = localIdx + rowOffset
                val pkKey = tableSchema.primaryKey.joinToString(",") { colName ->
                    row.get(colName)?.asString() ?: "null"
                }
                if (pkKey in pkValuesFromPreviousFiles) {
                    errors.add(DataValidationError(
                        table    = tableSchema.tableName,
                        rowIndex = globalIdx,
                        field    = null,
                        line     = null,
                        message  = "Duplicate primary key {$pkKey} found across data files" +
                                " for table '${tableSchema.tableName}'"
                    ))
                }
                thisFilePkKeys.add(pkKey)
                tableRows.add(row)
            }
            pkValuesFromPreviousFiles.addAll(thisFilePkKeys)

            fileStats.add(FileStats(filePath, tableSchema.tableName, loadResult.rows.size))
            mergedLineIndex = DataFileLoader.LineIndex.merge(mergedLineIndex, loadResult.lineIndex, rowOffset)
        }

        return Triple(tableRows, errors, fileStats)
    }

    /**
     * Generates SQL statements for all tables in the given order using their
     * pre-loaded, pre-validated rows.
     */
    private fun buildAllStatements(
        sortedTables: List<TableSchema>,
        allRows: Map<String, List<JsonNode>>
    ): List<GenerationResult.NamedStatement> {

        val statements       = mutableListOf<GenerationResult.NamedStatement>()
        val generatorContext = GeneratorContext()

        for (tableSchema in sortedTables) {
            val rows = allRows[tableSchema.tableName] ?: continue

            val generators: Map<String, ColumnGenerator> = tableSchema.columns
                .filter { col -> col.default?.kind == DefaultType.GENERATOR }
                .associate { col ->
                    col.name to GeneratorParser.parse(
                        expression       = col.default!!.value,
                        generatorContext = generatorContext
                    )
                }
            generators.values.forEach { it.reset() }

            for ((rowIndex, rowNode) in rows.withIndex()) {
                val baseFields      = flattenNode(rowNode)
                val generatedFields = generators
                    .filter { (colName, _) -> colName !in baseFields }
                    .mapValues { (_, gen) -> gen.next(rowIndex) }

                val mergedFields = generatedFields + baseFields

                val dataRow = DataRow(
                    tableName = tableSchema.tableName,
                    fields    = mergedFields,
                    schema    = tableSchema
                )

                val sql = dialect.generateUpsert(dataRow)
                statements.add(GenerationResult.NamedStatement(tableSchema.tableName, rowIndex, sql))

                for ((colName, value) in mergedFields) {
                    generatorContext.recordGeneratedValue(tableSchema.tableName, colName, value)
                }
            }
        }

        return statements
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Node flattening utilities (shared with dialect)
    // ─────────────────────────────────────────────────────────────────────────

    private fun flattenNode(node: JsonNode): Map<String, Any?> =
        buildMap {
            node.properties().forEach { entry ->
                put(entry.key, nodeToValue(entry.value))
            }
        }

    private fun nodeToValue(node: JsonNode): Any? = when {
        node.isNull                   -> null
        node.isBoolean                -> node.booleanValue()
        node.isInt                    -> node.intValue()
        node.isLong                   -> node.longValue()
        node.isDouble || node.isFloat -> node.doubleValue()
        node.isBigDecimal             -> node.decimalValue()
        node.isString                 -> node.stringValue()
        node.isObject || node.isArray -> node
        else                          -> node.asString()
    }
}
