
---- name_prefix -----
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 10, 'AGENT', 'Agent', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 20, 'BRIGADIER', 'Brig. Gen.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 40, 'CAPTAIN', 'Capt.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 50, 'CEO', 'CEO', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 60, 'COLONEL', 'Colonel', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 70, 'COMMISSNR', 'Commissioner', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 80, 'DR', 'Dr.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 90, 'ESTATE', 'The Estate of', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 100, 'GENERAL', 'General', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 110, 'HONORABLE', 'The Honorable', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 120, 'JUDGE', 'Judge', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 130, 'LADY', 'Lady', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 140, 'LT', 'Lt.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 150, 'LTGENERAL', 'Lt. Gen.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 160, 'MAJOR', 'Major', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 170, 'MAJORGEN', 'Maj. Gen.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 180, 'MISS', 'Miss', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 190, 'MONSIGNOR', 'Monsignor', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 200, 'MR', 'Mr.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 210, 'MRS', 'Mrs.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 220, 'MS', 'Ms.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 230, 'OFFICER', 'Officer', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 240, 'PROFESSOR', 'Prof.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 250, 'RABBI', 'Rabbi', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 260, 'REVEREND', 'Rev.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 270, 'REPRESENTATIVE', 'Rep.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 280, 'SENATOR', 'Sen.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 290, 'SGT', 'Sgt.', NULL, NULL, NULL, NULL);
INSERT INTO system_code (system_code_id, row_version, create_user, create_oper, create_ts, update_user, update_oper, update_ts, row_source, table_name, code_order, code_value, code_label, alternate_value, system_code_custom_class, system_code_custom_data, descr_text)
VALUES (nextval('system_code_id_seq'), 1, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'SYSTEM:9999999', 'SYSTEM:9999999', CURRENT_TIMESTAMP, 'BOOT_90000', 'name_prefix', 300, 'SISTER', 'Sister', NULL, NULL, NULL, NULL);