-- ============================================================
-- Generated by Knoppen version 0.5.0
-- User:      dutch
-- Generated: 2026-06-30 20:07:24
-- ------------------------------------------------------------
-- Tables:
--   tag:                 6 statement(s)
--   users:               7 statement(s)
--   post:                6 statement(s)
--   post_tag:            8 statement(s)
--   audit_log:           9 statement(s)
--   post_approval:       6 statement(s)
-- ============================================================

-- Table: tag, row[0]
INSERT INTO code_sample.tag (
    "id",
    "name",
    "column_order"
)
VALUES (
    1,
    'technology',
    10
)
ON CONFLICT (id) DO NOTHING
;

-- Table: tag, row[1]
INSERT INTO code_sample.tag (
    "id",
    "name",
    "column_order"
)
VALUES (
    2,
    'science',
    20
)
ON CONFLICT (id) DO NOTHING
;

-- Table: tag, row[2]
INSERT INTO code_sample.tag (
    "id",
    "name",
    "column_order"
)
VALUES (
    3,
    'health',
    30
)
ON CONFLICT (id) DO NOTHING
;

-- Table: tag, row[3]
INSERT INTO code_sample.tag (
    "id",
    "name",
    "column_order"
)
VALUES (
    4,
    'politics',
    40
)
ON CONFLICT (id) DO NOTHING
;

-- Table: tag, row[4]
INSERT INTO code_sample.tag (
    "id",
    "name",
    "column_order"
)
VALUES (
    5,
    'sports',
    50
)
ON CONFLICT (id) DO NOTHING
;

-- Table: tag, row[5]
INSERT INTO code_sample.tag (
    "id",
    "name",
    "column_order"
)
VALUES (
    3,
    'THIS_SHOULD_NOT_APPEAR',
    60
)
ON CONFLICT (id) DO NOTHING
;

-- Table: users, row[0]
INSERT INTO code_sample.users (
    "id",
    "source",
    "type",
    "createTs",
    "approvedTs",
    "username",
    "metadata"
)
VALUES (
    1,
    'Knoppen',
    'ADMIN',
    CURRENT_TIMESTAMP,
    '2023-06-01 09:00:00+00'::timestamp,
    'alice',
    '[]'::jsonb
)
ON CONFLICT (id)
DO UPDATE SET
    "source" = EXCLUDED."source",
        "type" = EXCLUDED."type",
        "approvedTs" = EXCLUDED."approvedTs",
        "username" = EXCLUDED."username",
        "metadata" = EXCLUDED."metadata"
;

-- Table: users, row[1]
INSERT INTO code_sample.users (
    "id",
    "source",
    "type",
    "createTs",
    "approvedTs",
    "username",
    "metadata"
)
VALUES (
    2,
    'Knoppen',
    'SUPERVISOR',
    CURRENT_TIMESTAMP,
    '2022-11-15 14:30:00+00'::timestamp,
    'bob',
    '[]'::jsonb
)
ON CONFLICT (id)
DO UPDATE SET
    "source" = EXCLUDED."source",
        "type" = EXCLUDED."type",
        "approvedTs" = EXCLUDED."approvedTs",
        "username" = EXCLUDED."username",
        "metadata" = EXCLUDED."metadata"
;

-- Table: users, row[2]
INSERT INTO code_sample.users (
    "id",
    "source",
    "type",
    "createTs",
    "approvedTs",
    "username",
    "metadata"
)
VALUES (
    2,
    'Knoppen',
    'ADMIN',
    CURRENT_TIMESTAMP,
    '2025-01-01 10:00:00+00'::timestamp,
    'bob',
    '[]'::jsonb
)
ON CONFLICT (id)
DO UPDATE SET
    "source" = EXCLUDED."source",
        "type" = EXCLUDED."type",
        "approvedTs" = EXCLUDED."approvedTs",
        "username" = EXCLUDED."username",
        "metadata" = EXCLUDED."metadata"
;

-- Table: users, row[3]
INSERT INTO code_sample.users (
    "id",
    "source",
    "type",
    "createTs",
    "approvedTs",
    "username",
    "metadata"
)
VALUES (
    6,
    'Knoppen',
    'USER',
    CURRENT_TIMESTAMP,
    '2019-01-01 00:00:00+00'::timestamp,
    'frank',
    '[]'::jsonb
)
ON CONFLICT (id)
DO UPDATE SET
    "source" = EXCLUDED."source",
        "type" = EXCLUDED."type",
        "approvedTs" = EXCLUDED."approvedTs",
        "username" = EXCLUDED."username",
        "metadata" = EXCLUDED."metadata"
;

-- Table: users, row[4]
INSERT INTO code_sample.users (
    "id",
    "source",
    "type",
    "createTs",
    "approvedTs",
    "username",
    "metadata"
)
VALUES (
    3,
    'Knoppen',
    'USER',
    CURRENT_TIMESTAMP,
    '2024-01-10 08:00:00+00'::timestamp,
    'carol',
    '[]'::jsonb
)
ON CONFLICT (id)
DO UPDATE SET
    "source" = EXCLUDED."source",
        "type" = EXCLUDED."type",
        "approvedTs" = EXCLUDED."approvedTs",
        "username" = EXCLUDED."username",
        "metadata" = EXCLUDED."metadata"
;

-- Table: users, row[5]
INSERT INTO code_sample.users (
    "id",
    "source",
    "type",
    "createTs",
    "username",
    "metadata"
)
VALUES (
    4,
    'Knoppen',
    'USER',
    CURRENT_TIMESTAMP,
    'dave',
    '[]'::jsonb
)
ON CONFLICT (id)
DO UPDATE SET
    "source" = EXCLUDED."source",
        "type" = EXCLUDED."type",
        "username" = EXCLUDED."username",
        "metadata" = EXCLUDED."metadata"
;

-- Table: users, row[6]
INSERT INTO code_sample.users (
    "id",
    "source",
    "type",
    "createTs",
    "approvedTs",
    "username",
    "metadata"
)
VALUES (
    5,
    'ManualEntry',
    'SUPERVISOR',
    CURRENT_TIMESTAMP,
    '2023-03-20 12:00:00+00'::timestamp,
    'eve',
    '[]'::jsonb
)
ON CONFLICT (id)
DO UPDATE SET
    "source" = EXCLUDED."source",
        "type" = EXCLUDED."type",
        "approvedTs" = EXCLUDED."approvedTs",
        "username" = EXCLUDED."username",
        "metadata" = EXCLUDED."metadata"
;

-- Table: post, row[0]
INSERT INTO code_sample.post (
    "id",
    "user_id",
    "title",
    "percent_approved",
    "column_order"
)
VALUES (
    100,
    1,
    'Introduction to PostgreSQL',
    95.0,
    10
)
ON CONFLICT (id)
DO UPDATE SET
    "title" = EXCLUDED."title",
        "percent_approved" = EXCLUDED."percent_approved",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post, row[1]
INSERT INTO code_sample.post (
    "id",
    "user_id",
    "title",
    "percent_approved",
    "column_order"
)
VALUES (
    101,
    2,
    'Advanced Indexing Strategies',
    87.5,
    20
)
ON CONFLICT (id)
DO UPDATE SET
    "title" = EXCLUDED."title",
        "percent_approved" = EXCLUDED."percent_approved",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post, row[2]
INSERT INTO code_sample.post (
    "id",
    "user_id",
    "title",
    "percent_approved",
    "column_order"
)
VALUES (
    102,
    1,
    'JSON and JSONB in Postgres',
    91.25,
    30
)
ON CONFLICT (id)
DO UPDATE SET
    "title" = EXCLUDED."title",
        "percent_approved" = EXCLUDED."percent_approved",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post, row[3]
INSERT INTO code_sample.post (
    "id",
    "user_id",
    "title",
    "percent_approved",
    "column_order"
)
VALUES (
    103,
    3,
    'Getting Started with SQL',
    78.0,
    40
)
ON CONFLICT (id)
DO UPDATE SET
    "title" = EXCLUDED."title",
        "percent_approved" = EXCLUDED."percent_approved",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post, row[4]
INSERT INTO code_sample.post (
    "id",
    "user_id",
    "title",
    "percent_approved",
    "column_order"
)
VALUES (
    104,
    5,
    'Query Optimization Tips',
    88.75,
    50
)
ON CONFLICT (id)
DO UPDATE SET
    "title" = EXCLUDED."title",
        "percent_approved" = EXCLUDED."percent_approved",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post, row[5]
INSERT INTO code_sample.post (
    "id",
    "user_id",
    "title",
    "percent_approved",
    "column_order"
)
VALUES (
    101,
    2,
    'Advanced Indexing Strategies - Revised',
    92.0,
    60
)
ON CONFLICT (id)
DO UPDATE SET
    "title" = EXCLUDED."title",
        "percent_approved" = EXCLUDED."percent_approved",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post_tag, row[0]
INSERT INTO code_sample.post_tag (
    "post_id",
    "tag_id",
    "column_order"
)
VALUES (
    100,
    1,
    10
)
ON CONFLICT (post_id, tag_id) DO NOTHING
;

-- Table: post_tag, row[1]
INSERT INTO code_sample.post_tag (
    "post_id",
    "tag_id",
    "column_order"
)
VALUES (
    100,
    2,
    20
)
ON CONFLICT (post_id, tag_id) DO NOTHING
;

-- Table: post_tag, row[2]
INSERT INTO code_sample.post_tag (
    "post_id",
    "tag_id",
    "column_order"
)
VALUES (
    101,
    1,
    30
)
ON CONFLICT (post_id, tag_id) DO NOTHING
;

-- Table: post_tag, row[3]
INSERT INTO code_sample.post_tag (
    "post_id",
    "tag_id",
    "column_order"
)
VALUES (
    102,
    3,
    40
)
ON CONFLICT (post_id, tag_id) DO NOTHING
;

-- Table: post_tag, row[4]
INSERT INTO code_sample.post_tag (
    "post_id",
    "tag_id",
    "column_order"
)
VALUES (
    103,
    4,
    50
)
ON CONFLICT (post_id, tag_id) DO NOTHING
;

-- Table: post_tag, row[5]
INSERT INTO code_sample.post_tag (
    "post_id",
    "tag_id",
    "column_order"
)
VALUES (
    104,
    1,
    60
)
ON CONFLICT (post_id, tag_id) DO NOTHING
;

-- Table: post_tag, row[6]
INSERT INTO code_sample.post_tag (
    "post_id",
    "tag_id",
    "column_order"
)
VALUES (
    104,
    2,
    70
)
ON CONFLICT (post_id, tag_id) DO NOTHING
;

-- Table: post_tag, row[7]
INSERT INTO code_sample.post_tag (
    "post_id",
    "tag_id",
    "column_order"
)
VALUES (
    100,
    1,
    80
)
ON CONFLICT (post_id, tag_id) DO NOTHING
;

-- Table: audit_log, row[0]
INSERT INTO code_sample.audit_log (
    "id",
    "user_id",
    "event",
    "event_ts",
    "notes"
)
VALUES (
    1000,
    1,
    'USER_CREATED',
    '2026-07-01 01:07:24Z'::timestamp,
    'Bootstrap insert -- alice'
)
ON CONFLICT (id) DO NOTHING
;

-- Table: audit_log, row[1]
INSERT INTO code_sample.audit_log (
    "id",
    "user_id",
    "event",
    "event_ts",
    "notes"
)
VALUES (
    1001,
    2,
    'USER_CREATED',
    '2026-06-30 19:07:24Z'::timestamp,
    'Bootstrap insert -- bob'
)
ON CONFLICT (id) DO NOTHING
;

-- Table: audit_log, row[2]
INSERT INTO code_sample.audit_log (
    "id",
    "post_id",
    "event",
    "event_ts",
    "notes"
)
VALUES (
    1002,
    100,
    'POST_CREATED',
    '2026-06-30 13:07:24Z'::timestamp,
    'Post 100 created'
)
ON CONFLICT (id) DO NOTHING
;

-- Table: audit_log, row[3]
INSERT INTO code_sample.audit_log (
    "id",
    "post_id",
    "event",
    "event_ts",
    "notes"
)
VALUES (
    1003,
    101,
    'POST_CREATED',
    '2026-06-30 07:07:24Z'::timestamp,
    'Post 101 created'
)
ON CONFLICT (id) DO NOTHING
;

-- Table: audit_log, row[4]
INSERT INTO code_sample.audit_log (
    "id",
    "post_id",
    "event",
    "event_ts",
    "notes"
)
VALUES (
    1004,
    101,
    'POST_UPDATED',
    '2026-06-30 01:07:24Z'::timestamp,
    'Post 101 revised title and approval score'
)
ON CONFLICT (id) DO NOTHING
;

-- Table: audit_log, row[5]
INSERT INTO code_sample.audit_log (
    "id",
    "post_id",
    "event",
    "event_ts"
)
VALUES (
    1005,
    102,
    'POST_APPROVED',
    '2026-06-29 19:07:24Z'::timestamp
)
ON CONFLICT (id) DO NOTHING
;

-- Table: audit_log, row[6]
INSERT INTO code_sample.audit_log (
    "id",
    "post_id",
    "event",
    "event_ts"
)
VALUES (
    1006,
    103,
    'POST_REJECTED',
    '2026-06-29 13:07:24Z'::timestamp
)
ON CONFLICT (id) DO NOTHING
;

-- Table: audit_log, row[7]
INSERT INTO code_sample.audit_log (
    "id",
    "post_id",
    "event",
    "event_ts"
)
VALUES (
    1007,
    104,
    'POST_APPROVED',
    '2026-06-29 07:07:24Z'::timestamp
)
ON CONFLICT (id) DO NOTHING
;

-- Table: audit_log, row[8]
INSERT INTO code_sample.audit_log (
    "id",
    "post_id",
    "event",
    "event_ts",
    "notes"
)
VALUES (
    1002,
    100,
    'POST_UPDATED',
    '2026-06-29 01:07:24Z'::timestamp,
    'THIS_SHOULD_NOT_APPEAR'
)
ON CONFLICT (id) DO NOTHING
;

-- Table: post_approval, row[0]
INSERT INTO code_sample.post_approval (
    "id",
    "post_id",
    "approver_id",
    "decision",
    "decided_ts",
    "column_order"
)
VALUES (
    2000,
    100,
    2,
    'APPROVED',
    '2025-02-01 10:00:00+00'::timestamp,
    10
)
ON CONFLICT (post_id, approver_id)
DO UPDATE SET
    "decision" = EXCLUDED."decision",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post_approval, row[1]
INSERT INTO code_sample.post_approval (
    "id",
    "post_id",
    "approver_id",
    "decision",
    "decided_ts",
    "column_order"
)
VALUES (
    2001,
    101,
    2,
    'REJECTED',
    '2025-02-02 11:00:00+00'::timestamp,
    20
)
ON CONFLICT (post_id, approver_id)
DO UPDATE SET
    "decision" = EXCLUDED."decision",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post_approval, row[2]
INSERT INTO code_sample.post_approval (
    "id",
    "post_id",
    "approver_id",
    "decision",
    "decided_ts",
    "column_order"
)
VALUES (
    2002,
    102,
    5,
    'APPROVED',
    '2025-02-03 09:30:00+00'::timestamp,
    30
)
ON CONFLICT (post_id, approver_id)
DO UPDATE SET
    "decision" = EXCLUDED."decision",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post_approval, row[3]
INSERT INTO code_sample.post_approval (
    "id",
    "post_id",
    "approver_id",
    "decision",
    "decided_ts",
    "column_order"
)
VALUES (
    2003,
    103,
    5,
    'ABSTAINED',
    '2025-02-04 14:00:00+00'::timestamp,
    40
)
ON CONFLICT (post_id, approver_id)
DO UPDATE SET
    "decision" = EXCLUDED."decision",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post_approval, row[4]
INSERT INTO code_sample.post_approval (
    "id",
    "post_id",
    "approver_id",
    "decision",
    "decided_ts",
    "column_order"
)
VALUES (
    2004,
    104,
    2,
    'APPROVED',
    '2025-02-05 16:00:00+00'::timestamp,
    50
)
ON CONFLICT (post_id, approver_id)
DO UPDATE SET
    "decision" = EXCLUDED."decision",
        "column_order" = EXCLUDED."column_order"
;

-- Table: post_approval, row[5]
INSERT INTO code_sample.post_approval (
    "id",
    "post_id",
    "approver_id",
    "decision",
    "decided_ts",
    "column_order"
)
VALUES (
    9999,
    101,
    2,
    'APPROVED',
    '2099-01-01 00:00:00+00'::timestamp,
    60
)
ON CONFLICT (post_id, approver_id)
DO UPDATE SET
    "decision" = EXCLUDED."decision",
        "column_order" = EXCLUDED."column_order"
;
